[package]
name = "openwebide-core"
description = "Shared domain types for Open WebIDE"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
base64 = { workspace = true }
ec4rs = { version = "1.2", features = ["allow-empty-values"] }
html5ever = "0.40"
ignore = "0.4.33"
regex = "1.13.1"
regex-automata = { version = "0.4.18", default-features = false, features = ["std"] }
unicode-segmentation = "1.13.3"
unicode-width = "0.2.2"
serde = { workspace = true }
serde_json = { workspace = true }

tree-sitter = { version = "0.27.0", optional = true }
tree-sitter-rust = { version = "0.24.2", optional = true }

[features]
test-support = []
editor-parser = ["dep:tree-sitter", "dep:tree-sitter-rust"]

[dev-dependencies]
futures = { workspace = true }
proptest = "1.11"


[lints]
workspace = true
