[package]
name = "openwebide-core"
description = "Shared domain types for Open WebIDE"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
base64 = { workspace = true }
ec4rs = { version = "1.2", features = ["allow-empty-values"] }
html5ever = "0.40"
ignore = "0.4.33"
serde = { workspace = true }
serde_json = { workspace = true }

[features]
test-support = []

[dev-dependencies]
futures = { workspace = true }
proptest = "1.11"


[lints]
workspace = true
