//! Grammar descriptors extend the shared parser without another editor workflow.
use crate::highlight::Language;

/// Custom providers use the same incremental update, limits, cancellation and fold policy.
#[derive(Clone, Copy)]
pub struct SyntaxProvider {
    pub language: Language,
    pub grammar: fn() -> tree_sitter::Language,
    pub fold_nodes: &'static [&'static str],
    /// Nodes whose parent supplies the visible fold header (Python suites).
    pub parent_headers: &'static [&'static str],
}

pub const SYNTAX_PROVIDERS: &[SyntaxProvider] = &[
    SyntaxProvider {
        language: Language::Rust,
        grammar: || tree_sitter_rust::LANGUAGE.into(),
        parent_headers: &[],
        fold_nodes: &[
            "block",
            "declaration_list",
            "enum_variant_list",
            "field_declaration_list",
            "match_block",
            "use_list",
            "token_tree",
            "block_comment",
            "array_expression",
            "arguments",
            "parameters",
            "tuple_expression",
            "raw_string_literal",
        ],
    },
    SyntaxProvider {
        language: Language::JavaScript,
        grammar: || tree_sitter_javascript::LANGUAGE.into(),
        parent_headers: &[],
        fold_nodes: &[
            "statement_block",
            "class_body",
            "object",
            "array",
            "arguments",
            "formal_parameters",
            "template_string",
            "comment",
            "jsx_element",
        ],
    },
    SyntaxProvider {
        language: Language::Jsx,
        grammar: || tree_sitter_javascript::LANGUAGE.into(),
        parent_headers: &[],
        fold_nodes: &[
            "statement_block",
            "class_body",
            "object",
            "array",
            "arguments",
            "formal_parameters",
            "template_string",
            "comment",
            "jsx_element",
        ],
    },
    SyntaxProvider {
        language: Language::TypeScript,
        grammar: || tree_sitter_typescript::LANGUAGE_TYPESCRIPT.into(),
        parent_headers: &[],
        fold_nodes: &[
            "statement_block",
            "class_body",
            "object",
            "array",
            "arguments",
            "formal_parameters",
            "template_string",
            "comment",
            "interface_body",
            "enum_body",
            "object_type",
        ],
    },
    SyntaxProvider {
        language: Language::Tsx,
        grammar: || tree_sitter_typescript::LANGUAGE_TSX.into(),
        parent_headers: &[],
        fold_nodes: &[
            "statement_block",
            "class_body",
            "object",
            "array",
            "arguments",
            "formal_parameters",
            "template_string",
            "comment",
            "interface_body",
            "enum_body",
            "object_type",
            "jsx_element",
        ],
    },
    SyntaxProvider {
        language: Language::Python,
        grammar: || tree_sitter_python::LANGUAGE.into(),
        parent_headers: &["block"],
        fold_nodes: &[
            "block",
            "list",
            "dictionary",
            "set",
            "tuple",
            "argument_list",
            "parameters",
            "string",
            "comment",
        ],
    },
    SyntaxProvider {
        language: Language::Java,
        grammar: || tree_sitter_java::LANGUAGE.into(),
        parent_headers: &[],
        fold_nodes: &[
            "block",
            "class_body",
            "enum_body",
            "annotation_type_body",
            "interface_body",
            "array_initializer",
            "argument_list",
            "formal_parameters",
            "block_comment",
        ],
    },
    SyntaxProvider {
        language: Language::CSharp,
        grammar: || tree_sitter_c_sharp::LANGUAGE.into(),
        parent_headers: &[],
        fold_nodes: &[
            "block",
            "declaration_list",
            "initializer_expression",
            "argument_list",
            "parameter_list",
            "switch_body",
            "interpolated_string_expression",
            "verbatim_string_literal",
            "raw_string_literal",
            "comment",
        ],
    },
    SyntaxProvider {
        language: Language::Cpp,
        grammar: || tree_sitter_cpp::LANGUAGE.into(),
        parent_headers: &[],
        fold_nodes: &[
            "compound_statement",
            "field_declaration_list",
            "enumerator_list",
            "initializer_list",
            "argument_list",
            "parameter_list",
            "raw_string_literal",
            "comment",
        ],
    },
    SyntaxProvider {
        language: Language::C,
        grammar: || tree_sitter_c::LANGUAGE.into(),
        parent_headers: &[],
        fold_nodes: &[
            "compound_statement",
            "field_declaration_list",
            "enumerator_list",
            "initializer_list",
            "argument_list",
            "parameter_list",
            "comment",
        ],
    },
    SyntaxProvider {
        language: Language::Php,
        grammar: || tree_sitter_php::LANGUAGE_PHP.into(),
        parent_headers: &[],
        fold_nodes: &[
            "compound_statement",
            "declaration_list",
            "array_creation_expression",
            "arguments",
            "formal_parameters",
            "encapsed_string",
            "heredoc",
            "nowdoc",
            "comment",
        ],
    },
    SyntaxProvider {
        language: Language::Shell,
        grammar: || tree_sitter_bash::LANGUAGE.into(),
        parent_headers: &[],
        fold_nodes: &[
            "if_statement",
            "case_statement",
            "for_statement",
            "while_statement",
            "subshell",
            "compound_statement",
            "do_group",
            "heredoc_body",
            "array",
            "command_substitution",
        ],
    },
    SyntaxProvider {
        language: Language::Go,
        grammar: || tree_sitter_go::LANGUAGE.into(),
        parent_headers: &[],
        fold_nodes: &[
            "block",
            "field_declaration_list",
            "literal_value",
            "argument_list",
            "parameter_list",
            "raw_string_literal",
            "comment",
        ],
    },
    SyntaxProvider {
        language: Language::Html,
        grammar: || tree_sitter_html::LANGUAGE.into(),
        parent_headers: &[],
        fold_nodes: &["element", "script_element", "style_element", "comment"],
    },
    SyntaxProvider {
        language: Language::Css,
        grammar: || tree_sitter_css::LANGUAGE.into(),
        parent_headers: &[],
        fold_nodes: &["block", "comment"],
    },
];

pub fn syntax_provider(language: Language) -> Option<SyntaxProvider> {
    SYNTAX_PROVIDERS
        .iter()
        .find(|provider| provider.language == language)
        .copied()
}
